apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
resources:
  - sources/helmrepos.yaml
  - storage/nfs-provisioner/helmrelease.yaml
  - storage/nfs-provisioner/namespace.yaml
