apiVersion: apps/v1
kind: Deployment
metadata:
  name: stac
  namespace: stac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stac
  template:
    metadata:
      labels:
        app: stac
    spec:
      containers:
        - name: stac
          image: steeven9/el-impostor:test
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
