# Allow all Flux controllers to communicate with the Kubernetes API server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-server
  namespace: flux-system
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow HTTPS traffic on common API server ports
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
